// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Controllerstatus struct {
	Scaling       bool
	LastHeartbeat pgtype.Timestamp
}

type Databasemapping struct {
	Url  pgtype.Text
	From string
	To   string
}

type Dbconnerror struct {
	WorkerID    pgtype.UUID
	DbID        pgtype.UUID
	FailureTime pgtype.Timestamp
}

type Migration struct {
	Url  pgtype.Text
	From string
	To   string
}

type Migrationworker struct {
	Uuid          pgtype.UUID
	LastHeartbeat pgtype.Timestamp
	Uptime        pgtype.Interval
	WorkingOnFrom pgtype.Text
	WorkingOnTo   pgtype.Text
}

type Monitor struct {
	Uuid          pgtype.UUID
	LastHeartbeat pgtype.Timestamp
	Url           string
}

type Workermetric struct {
	Uuid           pgtype.UUID
	LastHeartbeat  pgtype.Timestamp
	Uptime         pgtype.Interval
	ReqPerSec      pgtype.Int4
	WritePerSec    pgtype.Int4
	ReadPerSec     pgtype.Int4
	ReqTotal       pgtype.Int8
	ReqFailed      pgtype.Int8
	DbAvailability pgtype.Float4
}
