services:
  controller:
    container_name: matrix-controller
    build:
      context: .
      dockerfile: docker/dev/Dockerfile #Change app environment here
    env_file:
      - env/.env
    environment:
      SHADOW: "false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "1234:1234"
    networks:
      - matrix-kingdom
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:1234/health" ]
      interval: 5s
      retries: 1
      timeout: 30s

  controller-shadow:
    container_name: matrix-controller-shadow
    build:
      context: .
      dockerfile: docker/dev/Dockerfile #Change app environment here
    env_file:
      - env/.env
    environment:
      SHADOW: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "1235:1235"
    networks:
      - matrix-kingdom
    depends_on:
      controller:
        condition: service_started
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:1235/health" ]
      interval: 5s
      retries: 1
      timeout: 30s

  mongo:
    image: mongo
    container_name: matrix-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - matrix-mongo_db:/data/db
    ports:
      - "27017:27017"
    networks:
      - matrix-kingdom

  mongo-express:
    image: mongo-express
    container_name: matrix-mongo_express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    ports:
      - "8079:8081"
    networks:
      - matrix-kingdom

#  postgres:
#    image: postgres
#    command: -c 'max_connections=1000'
#    container_name: matrix-pg
#    restart: unless-stopped
#    env_file:
#      - env/.env.database
#    volumes:
#      - matrix-pg_db:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#    networks:
#      - matrix-kingdom
#    healthcheck:
#      test: [ "CMD-SHELL", "sh -c 'pg_isready -U username -d db'" ]


networks:
  matrix-kingdom:
    name: matrix-kingdom

volumes:
  matrix-pg_db:
  matrix-mongo_db: